name: Shiba Inu

on:
  push:
    branches: [ '*' ]
    paths: ['src/**', 'tests/**', '.github/workflows/**']
    
  pull_request:
    branches: [ 'main' ]
    paths: ['src/**', 'tests/**', '.github/workflows/**']

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    # - name: Run quick smoke tests
    #   run: |
    #     pytest tests/ -q